In [9]:
import numpy as np
import pandas as pd

In [10]:
LinkNYC_usage = pd.read_csv('~/dss4/LinkNYC/wifi_related_csv/LinkNYC_Usage_Statistics.csv')
LinkNYC_usage

,Week,Sessions Per Week,Cumulative Sessions To Date,Bandwidth Utilization Per Week (TB),Cumulative Bandwidth Utilization To Date (TB),Average Session Duration,New Subscribers Per Week,Total Subscribers Per Week,Cumulative Subscribers To Date
0,Week of 2/29/2016,31523,161899,0.418,1.73,0:03:01,1022,2391,6116
1,Week of 3/7/2016,54896,216795,0.635,1.84,0:02:47,2216,4041,8357
2,Week of 3/14/2016,61217,285012,0.602,2.32,0:02:49,2587,4983,10984
3,Week of 3/21/2016,103613,381766,1.103,3.21,0:03:09,5223,8322,15920
4,Week of 3/28/2016,158420,540186,1.315,5.28,0:02:53,6235,10961,22232
5,Week of 4/4/2016,232615,772801,1.975,7.25,0:02:58,8558,15480,30901
6,Week of 4/11/2016,265788,1038587,2.045,9.29,0:02:41,8354,17622,39355
7,Week of 4/18/2016,295665,1334252,2.190,11.47,0:02:42,8918,19662,48412
8,Week of 4/25/2016,398208,1732457,3.260,14.74,0:02:55,13938,26751,62517
9,Week of 5/2/2016,461639,2194096,3.740,18.48,0:02:57,14630,30871,77352
10,Week of 5/9/2016,534479,2728575,4.390,22.87,0:02:56,15366,34288,92941
11,Week of 5/16/2016,564942,3293515,4.430,27.30,0:02:58,15536,36269,108671
12,Week of 5/23/2016,630668,3924182,5.030,32.33,0:02:55,16277,39053,125157
13,Week of 5/30/2016,626790,4550969,4.750,37.08,0:02:57,15618,40251,141040
14,Week of 6/6/2016,687625,5238591,5.490,42.57,0:02:57,15186,41830,156436
15,Week of 6/13/2016,714250,5952837,5.600,48.17,0:02:55,15492,43526,172136
16,Week of 6/20/2016,738350,6691186,5.600,53.77,0:02:55,16544,45667,188868
17,Week of 6/27/2016,752740,7443924,5.700,59.47,0:02:55,16445,46572,205533
18,Week of 7/4/2016,746462,8190384,6.190,65.66,0:03:06,18204,48709,223955
19,Week of 7/11/2016,893033,9083415,6.700,72.36,0:02:55,21429,56359,245704
20,Week of 7/18/2016,1035958,10119373,7.790,80.15,0:02:57,26371,64733,272394
21,Week of 7/25/2016,1193660,11313032,8.650,88.79,0:02:55,29405,71664,302184
22,Week of 8/1/2016,1377833,12697236,10.370,102.84,0:03:13,21611,67277,321912
23,Week of 8/8/2016,1585082,14282318,12.290,115.13,0:03:22,28378,73728,350592
24,Week of 8/15/2016,1663717,15946035,12.700,127.83,0:03:25,30799,79126,381696
25,Week of 8/21/2016,1775886,17721921,13.910,141.74,0:03:23,32248,83605,414213
26,Week of 8/29/2016,1641374,19363295,13.730,155.48,0:03:27,24616,77424,439082
27,Week of 9/5/2016,1728568,21091863,13.840,169.31,0:03:22,24129,78640,463460
28,Week of 9/12/2016,1822249,22914112,15.360,184.68,0:03:16,25714,83660,489405
29,Week of 9/19/2016,785022,23699134,16.420,191.10,0:03:16,10288,54908,499761
30,Week of 9/26/2016,2569162,28663930,19.310,224.59,0:04:59,30867,201612,607188
31,Week of 10/3/2016,2656233,31320163,20.080,244.67,0:05:16,34317,209943,641505
32,Week of 10/10/2016,2797828,34117991,21.420,266.09,0:05:26,30225,217831,671730
33,Week of 10/17/2016,2966555,37084545,22.580,288.67,0:06:45,25357,225031,697087
34,Week of 10/24/2016,3004361,40088906,21.370,310.04,0:06:41,30726,228912,727813
35,Week of 10/31/2016,3339811,43428717,26.130,336.17,0:05:50,36036,240833,763849
36,Week of 11/7/2016,3415825,46844542,26.960,363.13,0:05:37,20821,243175,784670
37,Week of 11/14/2016,3711319,50555861,26.270,389.40,0:05:08,28792,246763,813462
38,Week of 11/21/2016,3374213,53930074,24.520,413.64,0:06:04,31653,246122,845115
39,Week of 11/28/2016,3820644,57750718,27.010,440.64,0:08:05,25809,254982,870924
40,Week of 12/5/2016,3918249,61668967,27.750,468.39,NaN,24861,261267,895785
41,Week of 12/12/2016,3856446,65525413,27.530,495.92,0:05:59,25617,257312,921402
42,Week of 12/19/2016,4007559,69532972,29.020,524.94,0:05:50,40073,268875,961475
43,Week of 12/26/2016,4306985,73839957,30.770,555.71,0:08:09,42729,296875,1004204
44,Week of 1/2/2017,4020306,77860263,29.200,554.14,0:06:54,33774,283136,1037978
45,Week of 1/9/2017,3890622,81750885,26.750,611.66,0:07:07,21907,271031,1059885
46,Week of 1/16/2017,4160809,85911694,28.640,644.18,0:04:29,26696,278513,1086581
47,Week of 1/23/2017,4323824,90235518,30.260,678.13,0:04:29,24368,285875,1110949
48,Week of 1/30/2017,4656164,94891682,32.240,714.74,0:04:54,27572,296558,1138521
49,Week of 2/6/2017,4528495,99420177,31.070,750.13,0:04:55,23262,297366,1161783
50,Week of 2/13/2017,5080560,104500737,32.720,787.71,0:04:57,33196,322806,1194979
51,Week of 2/20/2017,5276948,109777685,36.250,829.40,0:04:24,33925,335773,1228904
52,Week of 2/27/2017,5395485,115173170,36.570,870.86,0:04:20,27546,337532,1256450
53,Week of 3/6/2017,5246526,120419696,36.080,911.88,0:04:22,24201,337109,1280651
54,Week of 3/13/2017,5089725,125509421,34.370,951.31,0:04:35,28588,329391,1309239
55,Week of 3/20/2017,5967035,131476456,39.910,996.62,0:04:25,30209,353800,1339448

In [11]:
LinkNYC_usage.count() # "Average Session Duration" needs imputation

Week                                             56
Sessions Per Week                                56
Cumulative Sessions To Date                      56
Bandwidth Utilization Per Week (TB)              56
Cumulative Bandwidth Utilization To Date (TB)    56
Average Session Duration                         55
New Subscribers Per Week                         56
Total Subscribers Per Week                       56
Cumulative Subscribers To Date                   56
dtype: int64

In [12]:
LinkNYC_usage["Average Session Duration"]

0     0:03:01
1     0:02:47
2     0:02:49
3     0:03:09
4     0:02:53
5     0:02:58
6     0:02:41
7     0:02:42
8     0:02:55
9     0:02:57
10    0:02:56
11    0:02:58
12    0:02:55
13    0:02:57
14    0:02:57
15    0:02:55
16    0:02:55
17    0:02:55
18    0:03:06
19    0:02:55
20    0:02:57
21    0:02:55
22    0:03:13
23    0:03:22
24    0:03:25
25    0:03:23
26    0:03:27
27    0:03:22
28    0:03:16
29    0:03:16
30    0:04:59
31    0:05:16
32    0:05:26
33    0:06:45
34    0:06:41
35    0:05:50
36    0:05:37
37    0:05:08
38    0:06:04
39    0:08:05
40        NaN
41    0:05:59
42    0:05:50
43    0:08:09
44    0:06:54
45    0:07:07
46    0:04:29
47    0:04:29
48    0:04:54
49    0:04:55
50    0:04:57
51    0:04:24
52    0:04:20
53    0:04:22
54    0:04:35
55    0:04:25
Name: Average Session Duration, dtype: object

In [13]:
time_list = LinkNYC_usage["Average Session Duration"].tolist()
print type(time_list[0])
adjusted_time_list = []
for time in time_list:
    try:
        adjusted_time_list.append(int(time[0])*3600 + int(time[2:4])*60 + int(time[5:7]))
        
    except:
        pass

<type 'str'>

In [14]:
for time in time_list:
    print time

0:03:01
0:02:47
0:02:49
0:03:09
0:02:53
0:02:58
0:02:41
0:02:42
0:02:55
0:02:57
0:02:56
0:02:58
0:02:55
0:02:57
0:02:57
0:02:55
0:02:55
0:02:55
0:03:06
0:02:55
0:02:57
0:02:55
0:03:13
0:03:22
0:03:25
0:03:23
0:03:27
0:03:22
0:03:16
0:03:16
0:04:59
0:05:16
0:05:26
0:06:45
0:06:41
0:05:50
0:05:37
0:05:08
0:06:04
0:08:05
nan
0:05:59
0:05:50
0:08:09
0:06:54
0:07:07
0:04:29
0:04:29
0:04:54
0:04:55
0:04:57
0:04:24
0:04:20
0:04:22
0:04:35
0:04:25

In [15]:
imputation_mean_total = int(np.mean(adjusted_time_list))
imputation_mean_total

251

In [16]:
imputation_mean_limited = int(np.mean(adjusted_time_list[30:51]))
imputation_mean_limited

348

In [17]:
imputation_median_total = int(np.median(adjusted_time_list))
imputation_median_total

203

In [18]:
imputation_median_limited = int(np.median(adjusted_time_list[30:51]))
imputation_median_limited

337

### Which imputing should I choose?... Let's use 'imputation_mean_total' first.

In [19]:
adjusted_time_list.insert(40, imputation_mean_total)
LinkNYC_usage["Average Session Duration"] = adjusted_time_list

### At first, I got this error here.

<img src = "../images/error.png", width=600, height=300>

<img src="../images/error(1).png", width=600, height=30>

### When I looked into it, I found this worng written data and fixed it.

<img src="../images/error_cause.png", width=600, height=30>

In [20]:
LinkNYC_usage = LinkNYC_usage.rename(columns = {"Average Session Duration":"Average Session Duration(sec)"})

In [21]:
LinkNYC_usage["Average Sessions Per Subscriber"] = LinkNYC_usage["Sessions Per Week"] / LinkNYC_usage["Total Subscribers Per Week"]

In [22]:
LinkNYC_usage.tail()

,Week,Sessions Per Week,Cumulative Sessions To Date,Bandwidth Utilization Per Week (TB),Cumulative Bandwidth Utilization To Date (TB),Average Session Duration(sec),New Subscribers Per Week,Total Subscribers Per Week,Cumulative Subscribers To Date,Average Sessions Per Subscriber
51,Week of 2/20/2017,5276948,109777685,36.25,829.40,264,33925,335773,1228904,15.715820
52,Week of 2/27/2017,5395485,115173170,36.57,870.86,260,27546,337532,1256450,15.985107
53,Week of 3/6/2017,5246526,120419696,36.08,911.88,262,24201,337109,1280651,15.563293
54,Week of 3/13/2017,5089725,125509421,34.37,951.31,275,28588,329391,1309239,15.451925
55,Week of 3/20/2017,5967035,131476456,39.91,996.62,265,30209,353800,1339448,16.865560

In [23]:
LinkNYC_usage.to_csv('~/dss4/LinkNYC/wifi_related_csv/(preprocessed)LinkNYC_Usage_Statistics.csv')

In [25]:
LinkNYC_usage = pd.read_csv('~/dss4/LinkNYC/wifi_related_csv/(preprocessed)LinkNYC_Usage_Statistics.csv')
LinkNYC_usage[35:55]

,Unnamed: 0,Week,Sessions Per Week,Cumulative Sessions To Date,Bandwidth Utilization Per Week (TB),Cumulative Bandwidth Utilization To Date (TB),Average Session Duration(sec),New Subscribers Per Week,Total Subscribers Per Week,Cumulative Subscribers To Date,Average Sessions Per Subscriber
35,35,Week of 10/31/2016,3339811,43428717,26.13,336.17,350,36036,240833,763849,13.867747
36,36,Week of 11/7/2016,3415825,46844542,26.96,363.13,337,20821,243175,784670,14.046777
37,37,Week of 11/14/2016,3711319,50555861,26.27,389.40,308,28792,246763,813462,15.040014
38,38,Week of 11/21/2016,3374213,53930074,24.52,413.64,364,31653,246122,845115,13.709514
39,39,Week of 11/28/2016,3820644,57750718,27.01,440.64,485,25809,254982,870924,14.983975
40,40,Week of 12/5/2016,3918249,61668967,27.75,468.39,251,24861,261267,895785,14.997106
41,41,Week of 12/12/2016,3856446,65525413,27.53,495.92,359,25617,257312,921402,14.987432
42,42,Week of 12/19/2016,4007559,69532972,29.02,524.94,350,40073,268875,961475,14.904915
43,43,Week of 12/26/2016,4306985,73839957,30.77,555.71,489,42729,296875,1004204,14.507739
44,44,Week of 1/2/2017,4020306,77860263,29.20,554.14,414,33774,283136,1037978,14.199205
45,45,Week of 1/9/2017,3890622,81750885,26.75,611.66,427,21907,271031,1059885,14.354897
46,46,Week of 1/16/2017,4160809,85911694,28.64,644.18,269,26696,278513,1086581,14.939371
47,47,Week of 1/23/2017,4323824,90235518,30.26,678.13,269,24368,285875,1110949,15.124876
48,48,Week of 1/30/2017,4656164,94891682,32.24,714.74,294,27572,296558,1138521,15.700686
49,49,Week of 2/6/2017,4528495,99420177,31.07,750.13,295,23262,297366,1161783,15.228691
50,50,Week of 2/13/2017,5080560,104500737,32.72,787.71,297,33196,322806,1194979,15.738741
51,51,Week of 2/20/2017,5276948,109777685,36.25,829.40,264,33925,335773,1228904,15.715820
52,52,Week of 2/27/2017,5395485,115173170,36.57,870.86,260,27546,337532,1256450,15.985107
53,53,Week of 3/6/2017,5246526,120419696,36.08,911.88,262,24201,337109,1280651,15.563293
54,54,Week of 3/13/2017,5089725,125509421,34.37,951.31,275,28588,329391,1309239,15.451925

### I might have imputed wrong value to week 40's Average Session Duration(sec) because it has a too big decreasing.